name: Verilog Simulation CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verilog-sim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog gtkwave

      - name: Run Verilog simulations
        run: |
          bash "6. Tools/Simulation/run_simulation.sh" 